//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.02.13 at 03:40:10 PM EET
//


package com.esempla.task.client.generate;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="storageFileGenerate" type="{http://spring.io/guides/gs-producing-web-service}storageFileGenerate" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "storageFileGenerate"
})
@XmlRootElement(name = "getAllStorageFileResponse")
public class GetAllStorageFileResponse {

    @XmlElement(required = true)
    protected List<StorageFileGenerate> storageFileGenerate;

    /**
     * Gets the value of the storageFileGenerate property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the storageFileGenerate property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStorageFileGenerate().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StorageFileGenerate }
     *
     *
     */
    public List<StorageFileGenerate> getStorageFileGenerate() {
        if (storageFileGenerate == null) {
            storageFileGenerate = new ArrayList<StorageFileGenerate>();
        }
        return this.storageFileGenerate;
    }

}
